import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation,Link,Routes,Route,Navigate} from 'react-router-dom';
import {QueryClient,QueryClientProvider,useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {api,authApi} from './api';
import './styles.css';

type User={id:string;name:string;email:string;role:'ADMIN'|'MANAGER'|'MEMBER'}; type Project={id:string;name:string;description:string;color:string;_count?:{tasks:number}}; type Task={id:string;title:string;description:string;status:string;priority:string;projectId:string;project?:{name:string;color:string};assignee?:{name:string}};
const qc=new QueryClient();
function Shell({children}:{children:React.ReactNode}){const nav=useNavigate();const loc=useLocation();const [user,setUser]=useState<User|null>(null);useEffect(()=>{authApi.me().then(x=>setUser(x.user)).catch(()=>{})},[]);if(!localStorage.getItem('flowdesk_token'))return <Navigate to="/login" replace/>;const logout=()=>{localStorage.removeItem('flowdesk_token');nav('/login')};return <div className="app"><aside><div className="brand"><span>◆</span> FlowDesk</div><div className="caption">WORKSPACE</div><Link className={loc.pathname==='/'?'active':''} to="/">Overview</Link><Link className={loc.pathname.startsWith('/projects')?'active':''} to="/projects">Projects</Link><Link className={loc.pathname.startsWith('/tasks')?'active':''} to="/tasks">Tasks</Link><Link className={loc.pathname==='/team'?'active':''} to="/team">Team</Link><div className="profile"><strong>{user?.name||'Loading…'}</strong><small>{user?.role||''}</small><button onClick={logout}>Sign out</button></div></aside><main>{children}</main></div>}
function Login(){const nav=useNavigate();const [email,setEmail]=useState('demo@flowdesk.local'),[password,setPassword]=useState('Demo123!'),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const x=await authApi.login({email,password});localStorage.setItem('flowdesk_token',x.token);nav('/')}catch(e){setError((e as Error).message)}};return <div className="auth"><div className="auth-card"><div className="brand">◆ FlowDesk</div><h1>Welcome back</h1><p>Sign in to your workspace.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={8}/></label>{error&&<div className="error">{error}</div>}<button className="primary">Sign in</button></form><div className="hint">Demo: demo@flowdesk.local / Demo123!</div></div></div>}
function Dashboard(){const {data,isLoading,error}=useQuery({queryKey:['dashboard'],queryFn:()=>api<any>('/dashboard')});if(isLoading)return <Page title="Overview"><Loading/></Page>;if(error)return <Page title="Overview"><ErrorState/></Page>;const s=data.stats;return <Page title="Overview" subtitle="A quick view of your team's momentum."><div className="grid stats"><Stat label="Projects" value={s.projects} icon="▦"/><Stat label="Open tasks" value={s.tasks-s.done} icon="✓"/><Stat label="Completed" value={`${data.completion}%`} icon="↗"/><Stat label="High priority" value={s.high} icon="!"/></div><div className="panel hero"><div><span className="eyebrow">TEAM MOMENTUM</span><h2>Keep the work moving.</h2><p>Your team has completed {data.completion}% of all tracked tasks.</p></div><div className="ring"><b>{data.completion}%</b></div></div></Page>}
function Stat({label,value,icon}:{label:string;value:any;icon:string}){return <div className="panel stat"><span className="stat-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Projects(){const q=useQuery({queryKey:['projects'],queryFn:()=>api<any>('/projects')});const [show,setShow]=useState(false);return <Page title="Projects" subtitle="Organize initiatives and track delivery."><div className="toolbar"><input placeholder="Search projects…"/><button className="primary" onClick={()=>setShow(true)}>+ New project</button></div>{q.isLoading?<Loading/>:q.error?<ErrorState/>:q.data.projects.length===0?<Empty text="No projects yet."/>:<div className="cards">{q.data.projects.map((p:Project)=><Link to={`/projects/${p.id}`} className="panel project" key={p.id}><span className="dot" style={{background:p.color}}/><div><h3>{p.name}</h3><p>{p.description}</p><small>{p._count?.tasks||0} tasks</small></div><span>→</span></Link>)}</div>}{show&&<ProjectModal close={()=>setShow(false)}/>}</Page>}
function ProjectModal({close}:{close:()=>void}){const qc=useQueryClient();const [name,setName]=useState(''),[description,setDescription]=useState('');const m=useMutation({mutationFn:()=>api('/projects',{method:'POST',body:JSON.stringify({name,description,color:'#7c3aed'})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['projects']});close()}});return <div className="modal"><form className="modal-card" onSubmit={e=>{e.preventDefault();m.mutate()}}><h2>New project</h2><label>Name<input autoFocus value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label>{m.error&&<div className="error">{(m.error as Error).message}</div>}<div className="actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Create</button></div></form></div>}
function ProjectDetail(){const id=useLocation().pathname.split('/').pop()!;const q=useQuery({queryKey:['project',id],queryFn:()=>api<any>(`/projects/${id}`)});if(q.isLoading)return <Page title="Project"><Loading/></Page>;if(q.error)return <Page title="Project"><ErrorState/></Page>;const p=q.data.project;return <Page title={p.name} subtitle={p.description}><div className="panel"><div className="section-head"><h2>Tasks</h2><Link className="primary" to="/tasks">Manage tasks</Link></div>{p.tasks.length?<div className="task-list">{p.tasks.map((t:Task)=><div className="task-row" key={t.id}><span className={`badge ${t.status.toLowerCase()}`}>{t.status.replace('_',' ')}</span><strong>{t.title}</strong><span>{t.assignee?.name||'Unassigned'}</span><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span></div>)}</div>:<Empty text="No tasks in this project."/>}</div></Page>}
function Tasks(){const q=useQuery({queryKey:['tasks'],queryFn:()=>api<any>('/tasks')});const [filter,setFilter]=useState('');const tasks=(q.data?.tasks||[]).filter((t:Task)=>!filter||t.status===filter);return <Page title="Tasks" subtitle="Prioritize, assign and finish the work."><div className="toolbar"><div className="seg"><button className={!filter?'selected':''} onClick={()=>setFilter('')}>All</button>{['TODO','IN_PROGRESS','DONE'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x.replace('_',' ')}</button>)}</div></div>{q.isLoading?<Loading/>:q.error?<ErrorState/>:tasks.length?<div className="panel task-list">{tasks.map((t:Task)=><div className="task-row" key={t.id}><span className={`badge ${t.status.toLowerCase()}`}>{t.status.replace('_',' ')}</span><div><strong>{t.title}</strong><small>{t.project?.name}</small></div><span>{t.assignee?.name||'Unassigned'}</span><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span></div>)}</div>:<Empty text="Nothing matches this filter."/>}</Page>}
function Team(){const q=useQuery({queryKey:['users'],queryFn:()=>api<any>('/users')});return <Page title="Team" subtitle="People and permissions in your workspace.">{q.isLoading?<Loading/>:q.error?<ErrorState/>:<div className="panel member-list">{q.data.users.map((u:User)=><div className="member" key={u.id}><div className="avatar">{u.name.split(' ').map(x=>x[0]).join('')}</div><div><strong>{u.name}</strong><small>{u.email}</small></div><span className="role">{u.role}</span></div>)}</div>}</Page>}
function Page({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <div className="content"><header><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="live"><i/> Live workspace</div></header>{children}</div>};function Loading(){return <div className="panel state">Loading…</div>}function ErrorState(){return <div className="panel state error">Something went wrong. Try again.</div>}function Empty({text}:{text:string}){return <div className="panel state"><h3>{text}</h3><p>There is nothing to show here yet.</p></div>}
function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Shell><Dashboard/></Shell>}/><Route path="/projects" element={<Shell><Projects/></Shell>}/><Route path="/projects/:id" element={<Shell><ProjectDetail/></Shell>}/><Route path="/tasks" element={<Shell><Tasks/></Shell>}/><Route path="/team" element={<Shell><Team/></Shell>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={qc}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></React.StrictMode>);
